export const rideStatus: { [key: string]: [string, number] } = {
  ACCEPTED: ["Active", 1],
  APPROACHING: ["Approaching", 1],
  ARRIVED: ["Arrived", 1],
  ARRIVING: ["Arriving", 1],
  CANCELED_BY_DISPATCHER: ["Canceled", 2],
  CANCELED_BY_DRIVER: ["Canceled", 2],
  CANCELED_BY_RIDER: ["Canceled", 2],
  COMPLETE: ["Complete", 1],
  CONFIRMED: ["Confirmed", 1],
  DROPPED_OFF: ["Complete", 1],
  FAILED: ["Error", 2],
  IN_TRANSIT: ["Active", 1],
  MISSED: ["Missed", 2],
  NO_DRIVERS_AVAILABLE: ["Error", 2],
  NO_SHOW: ["Missed", 2],
  PENDING: ["Pending", 1],
  PICKED_UP: ["Active", 1],
  REJECTED: ["Rejected", 2],
  REQUESTED: ["Pending", 1],
  REQUESTING: ["Pending", 1],
  RIDE_RECEIPT_READY: ["Complete", 1],
  SCHEDULED: ["Confirmed", 1],
};
